### ISSUE TITLE
Are contributions welcome?

### ISSUE THREAD

**Issue by mattijsbliek** [ryanolf/node-sonos-nfc#4]
Hey 👋

I'm planning to build a Raspberry Pi system based on this project, and I'd happily contribute some code. Before doing so, I thought it easiest to discuss first to see what you think 🙂

Would love to get your input on having the following changes:
* Add Prettier to the codebase to avoid syntax discussions. Created a PR [here](https://github.com/ryanolf/node-sonos-nfc/pull/3).
* Add `reset_playback_options_on_queue` setting like described in the existing README.
* Add option to stop playback when card is removed from reader.
* Replace console.log by a proper logger which doesn't output info messages in production.
* Split up `process_sonos_command.js` and `sonos_nfc.js` so individual parts can be unit tested.
* Add [Jest](https://jestjs.io/) and some tests.
* Convert project to Typescript? Happy to do so, not sure if this is desirable from your perspective.

Let me know what you think. All the best,

Mattijs

**Comment by ryanolf** [comment]
Hey @mattijsbliek, thanks for contributing and for the ideas. Yes, contributions are absolutely welcome!

I think these are all great ideas, and I'd happily roll all these things into the code. Especially if more folks start to contribute, having comprehensive testing and style linting are going to be important to help make sure the code doesn't break and doesn't become too difficult to read.

I'll take a look at your PR maybe later today. Thanks for the contribution!

**Comment by ryanolf** [comment]
Re: Typescript, it's not clear to me that it's worth the effort, but I wouldn't object to this at all if you want to do the work. How much benefit Typescript provides probably depends on how much the codebase grows in the future. I've shelved my immediate plans for adding features (e.g. add the ability to easily program cards), but if you think you or others will be adding features, a more robust language may make more sense. On the other hand, the current code works to do what it's supposed to. Adding type safety and compile-time checking of certain constraints won't make it perform any better.

**Comment by mattijsbliek** [comment]
Makes sense! Will take care of these others first. Also the ability to program cards would be really cool, might get to that at some point 🙂

Closing this issue for now, will have some more PRs incoming over the next few weeks 👍

**Comment by sirfelixw** [comment]
Hi everyone, I love this project and successfully implemented it in my home. There's only one thing I really miss: Being able to stop playback when the card is removed. @mattijsbliek you mentioned that you plan to add an "option to stop playback when card is removed from reader". Is there a version of this already or could you help me make that happen?

**Comment by ryanolf** [comment]
@sirfelixw This feature hasn't been implemented, though it wouldn't be too hard to do it. You'd need to add a setting in `usersettings.json` and then call into `process_sonos_command` with the appropriate "pause" command contingent on that setting from the `card.off` branch in `sosnos_nfc.js`.

**Comment by sirfelixw** [comment]
@ryanolf thanks for the super fast response. I'm new to Javascript. If someone has time to set up the required code changes, that would be amazing. I'd check them out and try to learn from seeing what changed. If not, that's also fine and I'll try to it with lots of trial and error myself.
